"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tmrm = require("azure-pipelines-task-lib/mock-run");
var path = require("path");
var taskPath = path.join(__dirname, '..', 'index.js');
var tmr = new tmrm.TaskMockRunner(taskPath);
tmr.setInput('version', 'version');
tmr.setInput('location', 'katalon');
tmr.setInput('executeArgs', 'executeArgs');
tmr.setInput('x11Display', 'x11Display');
tmr.setInput('xvfbConfiguration', 'xvfbConfiguration');
console.log("Call success");
tmr.run();
